dependencies:
- name: ipfs
  version: ~0.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: ipfs.enabled
  tags:
    - ipfs-cluster
- name: eosnode
  version: ~0.1.0
  repository: https://s3-us-west-2.amazonaws.com/liquidapps-helm-charts/
  condition: eosnode.enabled
  tags:
    - eosio
    - eosnode
- name: dspnode
  version: ~0.1.0
  repository: file://./dspnode
  condition: dspnode.enabled
  tags:
    - eosio
    - eosnode    