# Default values for dapp-dsp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


eosnode:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 1000Gi
  # Default values for dapp-dsp.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  enabled: true
  replicaCount: 1

  service:
    port: 8888
    type: ClusterIP
    loadBalancerSourceRanges: "0.0.0.0/0"
  
    
  resources: {}  # Optionally specify how much CPU and memory (RAM) each nodeos container needs.
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    
ipfs:
  enabled: true
  replicaCount: 1
  persistence:
    size: 100Gi
  service:
    type: LoadBalancer
dspnode:
  enabled: true
  replicaCount: 1

  image:
    repository: liquidapps/eosio-plugins
    tag: v1.6.1
    pullPolicy: Always

  service:
    port: 8888
    type: LoadBalancer
    loadBalancerSourceRanges: "0.0.0.0/0"