# Default values for dapp-dsp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


eosnode:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 1000Gi
  # Default values for dapp-dsp.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  service:
    port: 8888
    qport: 5556
    type: ClusterIP

  snapshot: false
  clear: false    
  resources: {}  # Optionally specify how much CPU and memory (RAM) each nodeos container needs.
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  moreargs:
    - --chain-state-db-size-mb=786432 
    - --reversible-blocks-db-size-mb=2048
    - --max-clients=150
    - --sync-fetch-span=2000
    - --http-server-address=0.0.0.0:8888 
    - --http-validate-host=false 
    - --force-all-checks
    - --disable-replay-opts
    - --max-transaction-time=5000
    - --abi-serializer-max-time-ms=15000 
    - --plugin=eosio::zmq_plugin
    - --zmq-enable-actions=true
    - --zmq-enable-transactions=true
    - --zmq-enable-push-socket=true
    - --zmq-sender-bind=tcp://0.0.0.0:5556
ipfs:
  enabled: true
  replicaCount: 1
  persistence:
    size: 100Gi
  service:
    type: LoadBalancer
dspnode:
  enabled: true
  replicaCount: 1

  image:
    repository: ubuntu
    tag: latest
    pullPolicy: Always

  service:
    port: 8888
    type: LoadBalancer
    loadBalancerSourceRanges: "0.0.0.0/0"