# Default values for dapp-dsp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


eosnode:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 100Gi
ipfs:
  enabled: true
  replicaCount: 1
  persistence:
    size: 100Gi
  service:
    type: LoadBalancer
dspnode:
  enabled: true
  replicaCount: 1
  service:
    type: LoadBalancer