{{- $intialKey := splitList "=KEY:" .Values.genesis.signatureProvider | first -}}
{{- $myDict := dict "initial_timestamp" .Values.genesis.initial_timestamp  "initial_key" $intialKey "initial_configuration" .Values.genesis.initial_configuration -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dapp-dsp.fullname" . }}
  labels:
    app: {{ include "dapp-dsp.name" . }}
    chart: {{ include "dapp-dsp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  genesis.json: |-
    {{ toJson $myDict }}
