apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eosnode.nodeosfullname" . }}
  labels:
    app: {{ include "eosnode.name" . }}
    chart: {{ include "eosnode.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodeos
      release: {{ .Release.Name }}
  serviceName: {{ include "eosnode.headlessname" . }}
  template:
    metadata:
      labels:
        app: nodeos
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - nodeos
            - -e
            - -p
            - eosio 
            - --plugin 
            - eosio::chain_plugin 
            - --plugin 
            - eosio::chain_api_plugin 
            - --data-dir=/eos.data 
            - --chain-state-db-size-mb=786432
            - --reversible-blocks-db-size-mb=2048
            - --max-clients=150
            - --sync-fetch-span=2000 
            - --http-server-address=0.0.0.0:8888 
            - --http-validate-host=false
            - --snapshot 
            - /eos.data/snapshots/snapshot-*.bin 
          args: {{ toJson .Values.args }}
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 9876
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/chain/get_info
              port: 8888
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/eosio/genesis.json
              subPath: genesis.json
{{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /eos.data
{{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "eosnode.fullname" . }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ include "eosnode.name" . }}
          chart: {{ include "eosnode.chart" . }}
          release: {{ .Release.Name }}
          heritage: {{ .Release.Service }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}        
      {{- end }}
{{- end }}