apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eosnode.nodeosfullname" . }}
  labels:
    app: {{ include "eosnode.name" . }}
    chart: {{ include "eosnode.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodeos
      release: {{ .Release.Name }}
  serviceName: {{ include "eosnode.headlessname" . }}
  template:
    metadata:
      labels:
        app: nodeos
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-data
          image: liquidapps/eosio-mainnet-loader
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: CLEAR_DB
            value: "{{ .Values.clear }}"
          volumeMounts:
            - name: data
              mountPath: /eos.data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
            - -ec
            - nodeos -e -p eosio --plugin eosio::chain_plugin --plugin eosio::chain_api_plugin --data-dir=/eos.data {{ include "eosnode.nodeargs" . }}
          args: {{ toJson .Values.args }}
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 9876
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/chain/get_info
              port: 8888
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: /eos.data
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "eosnode.fullname" . }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ include "eosnode.name" . }}
          chart: {{ include "eosnode.chart" . }}
          release: {{ .Release.Name }}
          heritage: {{ .Release.Service }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}        
      {{- end }}
