apiVersion: v1
kind: Service
metadata:
  name: {{ include "dspnode.dspfullname" . }}
  labels:
    app: {{ include "dspnode.name" . }}
    chart: {{ include "dspnode.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerSourceRanges: 
{{- range $index, $cidr := .Values.service.loadBalancerSourceRanges | split "," }}
    - {{ $cidr }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3115
      protocol: TCP
      name: api
    - port: 8812
      targetPort: 8812
      protocol: TCP
      name: webhook     
  selector:
    app: nodeos
    release: {{ .Release.Name }}
