apiVersion: v1
kind: Service
metadata:
  name: {{ include "dspnode.dspfullname" . }}
  labels:
    app: {{ include "dspnode.name" . }}
    chart: {{ include "dspnode.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerSourceRanges: 
{{- range $index, $cidr := .Values.service.loadBalancerSourceRanges | split "," }}
    - {{ $cidr }}
{{- end }}
  ports:
    - port: 3115
      targetPort: 3115
      nodePort: 30115
      protocol: TCP
      name: api
  selector:
    app: dspnode
    release: {{ .Release.Name }}
