apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dspnode.dspfullname" . }}
  labels:
    app: {{ include "dspnode.name" . }}
    chart: {{ include "dspnode.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dspnode
      release: {{ .Release.Name }}
  serviceName: {{ include "dspnode.headlessname" . }}
  template:
    metadata:
      labels:
        app: dspnode
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}-gw
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - node
            - services/dapp-services-node/index.js
          env:
          - name: DAPPSERVICES_CONTRACT
            value: "{{ .Values.contracts.dappservices }}"
          - name: DAPPSERVICES_CONTRACT_IPFS
            value: "{{ .Values.contracts.ipfs }}"
          - name: DAPPSERVICES_CONTRACT_LOG
            value: "{{ .Values.contracts.log }}"
          - name: NODEOS_CHAINID
            value: "{{ .Values.chainid }}"
          - name: NODEOS_HOST
            value: "{{ .Release.Name }}-nodeos"
          - name: NODEOS_PORT
            value: "38888"
          - name: DSP_ACCOUNT
            value: "{{ .Values.dspaccount }}"
          - name: DSP_PRIVATE_KEY
            value: "{{ .Values.dspkey }}"
          ports:
            - containerPort: 3115
              protocol: TCP
              name: api
            - containerPort: 8812
              protocol: TCP
              name: webhook
        - name: {{ .Chart.Name }}-demux
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - node
            - services/demux/index.js
          env:
          - name: NODEOS_CHAINID
            value: "{{ .Values.chainid }}"
          - name: NODEOS_HOST
            value: "{{ .Release.Name }}-nodeos"
          - name: NODEOS_PORT
            value: "38888"
          - name: NODEOS_ZMQ_PORT 
            value: "5557"
          - name: SOCKET_MODE
            value: "sub"
        - name: {{ .Chart.Name }}-ipfs-svc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - node
            - services/ipfs-dapp-service-node/index.js
          env:
          - name: DAPPSERVICES_CONTRACT
            value: "{{ .Values.contracts.dappservices }}"
          - name: DAPPSERVICES_CONTRACT_IPFS
            value: "{{ .Values.contracts.ipfs }}"
          - name: DAPPSERVICES_CONTRACT_LOG
            value: "{{ .Values.contracts.log }}"
          - name: NODEOS_CHAINID
            value: "{{ .Values.chainid }}"
          - name: NODEOS_HOST
            value: "{{ .Release.Name }}-nodeos"
          - name: NODEOS_PORT
            value: "38888"
          - name: IPFS_HOST
            value: "{{ .Chart.Name }}-ipfs"
          - name: DSP_ACCOUNT
            value: "{{ .Values.dspaccount }}"
          - name: DSP_PRIVATE_KEY
            value: "{{ .Values.dspkey }}"
          ports:
            - containerPort: 13115
              protocol: TCP
              name: ipfs
        - name: {{ .Chart.Name }}-log-svc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 13110
              protocol: TCP
              name: log
          command:
            - node
            - services/log-dapp-service-node/index.js
          env:
          - name: DAPPSERVICES_CONTRACT
            value: "{{ .Values.contracts.dappservices }}"
          - name: DAPPSERVICES_CONTRACT_IPFS
            value: "{{ .Values.contracts.ipfs }}"
          - name: DAPPSERVICES_CONTRACT_LOG
            value: "{{ .Values.contracts.log }}"
          - name: NODEOS_CHAINID
            value: "{{ .Values.chainid }}"
          - name: NODEOS_HOST
            value: "{{ .Release.Name }}-nodeos"
          - name: NODEOS_PORT
            value: "38888"
          - name: DSP_ACCOUNT
            value: "{{ .Values.dspaccount }}"
          - name: DSP_PRIVATE_KEY
            value: "{{ .Values.dspkey }}"
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "dspnode.fullname" . }}