# Default values for dapp-dsp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true
replicaCount: 1

image:
  repository: liquidapps/eosio-plugins
  tag: v1.6.1
  pullPolicy: Always

service:
  port: 8888
  type: LoadBalancer
  loadBalancerSourceRanges: "0.0.0.0/0"
 
# The argument passed to nodeos 
args:
  - --max-transaction-timetest 
  - "5000"
  - --abi-serializer-max-time-ms 
  - "15000"

clear: false
persistence:
  enabled: true
  # storageClass: "-"
  size: 1000Gi
  
resources: {}  # Optionally specify how much CPU and memory (RAM) each nodeos container needs.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
